[package]
name = "spending-tracker"
version = "0.3.1"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]
edition = "2018"

[dependencies]
axum = "0.4"
axum-extra = "0.1.2"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
#rust-embed = "5"
#mime_guess = "2"
metrics = "0.18"
metrics-exporter-prometheus = "0.8"
rusty-money = "0.4"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.2", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

