[package]
name = "spending-tracker"
version = "0.3.1"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-prom = "0.6.0"
actix-cors = "0.6.0"
#actix-files = "0.6.0-beta.8" TODO: use this
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rust-embed = "5"
mime_guess = "2"
rusty-money = "0.4"

