[workspace]
members = [
    "spending-tracker",
    "metro-schedule",
    "telegram-bot",
]
resolver = "2"

[profile.release]
opt-level = 3
overflow-checks = false
debug-assertions = false
lto = true
debug = false
panic = "abort"