[package]
name = "metro-schedule"
version = "0.1.0"
authors = ["Bryant Deters <bryantdeters@gmail.com"]
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-prom = "0.6.0"
anyhow = "1"
clap = "2.33.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4.6"
csv = "1"
rust-embed = "5"
nom = "7.1.1"
