[package]
name = "metro-schedule"
version = "0.2.0"
authors = ["Bryant Deters <bryantdeters@gmail.com"]
edition = "2021"

[dependencies]
axum = "0.6"
anyhow = "1"
clap = {version = "4.1.1", features = ["cargo"]}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4.23"
csv = "1"
rust-embed = "6.4.2"
nom = "7.1.1"
tokio = { version = "1", features = ["full"] }
