[package]
name = "telegram-chatbot"
version = "0.5.0"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.0.0-beta.10"
actix-web-prom = "0.6.0-beta.3"
teloxide = {version = "0.5", features = ["auto-send", "macros"]}
lazy_static = "1.4.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
regex = "1.3"
reqwest = {version ="0.11", features = ["json"]}
prometheus = "0.13"
tokio = { version =  "1.4.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.3"
spending-tracker = { package = "spending-tracker", path = "../spending-tracker" }
metro-schedule = { package = "metro-schedule", path = "../metro-schedule" }