[package]
name = "telegram-chatbot"
version = "0.4.2"
authors = ["Bryant Deters <bryantdeters@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.6"
actix-web-prom = "0.5"
teloxide = {version = "0.4", features = ["auto-send"]}
lazy_static = "1.4.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
regex = "1.3"
reqwest = "0.11"
prometheus = "0.12"
tokio = { version =  "1.3.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.3"
spending-tracker = { package = "spending-tracker", path = "../spending-tracker" }
metro-schedule = { package = "metro-schedule", path = "../metro-schedule" }